import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';

import Title from '../components/Title';
import Counter from '../components/Counter';
import useStore from '../lib/store';
import Layout from '../components/layout/Layout';

const UI: NextPage = () => {
  const { count, increment, decrement } = useStore();

  return (
    <>
      <Head>
        <title>UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="UI Page -w" />
        <div style={{ marginLeft: '5rem' }}>This page lives in the UI app (remote)</div>
        <Layout>
          <div style={{ marginLeft: '2rem' }}>
            <div>The s'boxed' container is not exposed by the UI remote, but used internally only</div>
          </div>
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  );
};

UI.getInitialProps = async () => {
  return {};
};

export default UI;
