
import React from "react";
import { createFederatedCatchAll } from "@module-federation/next-catchall";

const ErrorComponent = () => {
  return <h1>There was an error trying to load route</h1>;
};
const NotFoundComponent = () => {
  return <h1>4OH4 not found</h1>;
};
export default createFederatedCatchAll(
  process.env.REMOTES,
  ErrorComponent,
  NotFoundComponent
);

// import type { NextPage } from 'next'
// import React from 'react'
// import dynamic from 'next/dynamic'
// import Head from 'next/head'

// // Federated imports
// // const useStore = (await import('../fed-store/uiStore')).default
// // const Layout = dynamic(() => import('../fed-components/uiLayout'))
// // const Title = dynamic(() => import('ui/Title')) // This one should work
// // import Title from '../components/Title'
// const Title = dynamic(() => import('../components/Title'))
// // const Counter = dynamic(() => import('../fed-components/uiCounter'))

// const Home: NextPage = ({ data }: any) => {
//   // const { count, increment, decrement } = useStore()
//   return (
//     <>
//       <Head>
//         <title>Home</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>
//         {/* <div>Homes</div> */}
//         <Title text="Homes" />
//         {/* <Counter count={count} onIncrement={increment} onDecrement={decrement} /> */}
//         {/* <Layout>
//           <Title text="Home s" />
//         </Layout> */}
//         {data && <h3><span style={{ fontWeight: 'bold' }}>Data from API:</span> {JSON.stringify(data)}</h3>}
//       </main>
//     </>
//   )
// }

// Home.getInitialProps = async () => {
//   const res = await fetch('https://jsonplaceholder.typicode.com/todos/1');
//   const data = await res.json();
//   return { data };
// }

// export default Home