import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'

import Title from '../components/Title'
import Counter from '../components/Counter'
import useStore from '../lib/store'
import Layout from '../components/layout/Layout'

const UI: NextPage = () => {

  const { count, increment, decrement } = useStore()

  const shared = [
    'zustand',
    '@chakra-ui/react',
    '@chakra-ui/theme-tools',
    '@chakra-ui/system',
    '@chakra-ui/icons',
    '@emotion/react',
    '@emotion/styled',
  ]

  return (
    <>
      <Head>
        <title>UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Title text="UI Page" />
        <div style={{ marginLeft: '1.5rem' }}>This page lives in the UI app (remote)</div>
        <Layout>
          <div style={{ marginLeft: '2rem' }}>
            <div>The 'boxed' container is not exposed by the UI remote, but used internally only</div>
            <br />
            <pre>Shared:{JSON.stringify(shared, null, 2)}</pre>
          </div>
          <Counter count={count} onIncrement={increment} onDecrement={decrement} />
        </Layout>
      </main>
    </>
  )
}

UI.getInitialProps = async () => {
  return {};
}

export default UI
